package it.polimi.ingsw.Network;

public enum TypeofMessage {
    LOGINREQUEST,
    LOGINRESPONSE,
    GAMEINFO,
    GAMERESULT,
    SETTOWER,
    NEWGAME,
    LOADGAME,
    MOVEMOTHERNATURE,
    GAMEBOARDUPDATE,
    ERROR,
    GENERIC,
    CHOOSECLOUDTILE,
    CHOOSECARD,
    ALREADYUSED,

}
